DROP TABLE IF EXISTS LABA13_DB.ROLE;
CREATE TABLE LABA13_DB.ROLE (
role_id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(32) UNIQUE NOT NULL,
PRIMARY KEY (ROLE_ID)
);




DROP TABLE IF EXISTS LABA13_DB.USER;
CREATE TABLE LABA13_DB.USER (
user_id INT AUTO_INCREMENT NOT NULL,
login VARCHAR(30) UNIQUE NOT NULL,
password VARCHAR(64) NOT NULL,
email VARCHAR(46) UNIQUE NOT NULL,
firstName VARCHAR(32) NOT NULL,
lastName VARCHAR(32) NOT NULL,
birthday DATE NOT NULL,
id_role INT NOT NULL,
PRIMARY KEY (user_id),
FOREIGN KEY (id_role) REFERENCES LABA13_DB.ROLE (role_id) ON DELETE CASCADE
ON UPDATE CASCADE
);




